# Generated by Django 3.1 on 2022-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='response',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='tests',
            field=models.TextField(null=True),
        ),
    ]
