# Generated by Django 3.1 on 2022-02-06 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220206_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='upload',
            field=models.FileField(upload_to='%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp'])]),
        ),
    ]
