# Generated by Django 3.1 on 2022-02-06 12:31

import django.core.validators
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220206_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='upload',
            field=models.FileField(upload_to=tasks.models.directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp'])]),
        ),
    ]
