# Generated by Django 3.1 on 2022-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20220806_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
